[2025-05-01T06:00:53.012+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-01T06:00:53.079+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_diabetes_data.process_validation_data.process_validation_batches manual__2025-05-01T05:42:05.666671+00:00 [queued]>
[2025-05-01T06:00:53.100+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_diabetes_data.process_validation_data.process_validation_batches manual__2025-05-01T05:42:05.666671+00:00 [queued]>
[2025-05-01T06:00:53.102+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-05-01T06:00:53.131+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_validation_data.process_validation_batches> on 2025-05-01 05:42:05.666671+00:00
[2025-05-01T06:00:53.190+0000] {standard_task_runner.py:63} INFO - Started process 139 to run task
[2025-05-01T06:00:53.217+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_diabetes_data', 'process_validation_data.process_validation_batches', 'manual__2025-05-01T05:42:05.666671+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_store_data.py', '--cfg-path', '/tmp/tmp8v4hgnf0']
[2025-05-01T06:00:53.232+0000] {standard_task_runner.py:91} INFO - Job 126: Subtask process_validation_data.process_validation_batches
[2025-05-01T06:00:53.374+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_diabetes_data.process_validation_data.process_validation_batches manual__2025-05-01T05:42:05.666671+00:00 [running]> on host a60a20642f57
[2025-05-01T06:00:53.682+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_diabetes_data' AIRFLOW_CTX_TASK_ID='process_validation_data.process_validation_batches' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T05:42:05.666671+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T05:42:05.666671+00:00'
[2025-05-01T06:00:53.684+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-01T06:00:53.796+0000] {fetch_and_store_data.py:215} INFO - Procesando 2 batches para validation
[2025-05-01T06:00:53.799+0000] {fetch_and_store_data.py:117} INFO - Obteniendo validation batch 0 desde http://datapi:80/get-validation-batch/?batch_number=0
[2025-05-01T06:00:58.102+0000] {fetch_and_store_data.py:134} INFO - Obtenidos 15000 registros de validation batch 0
[2025-05-01T06:00:58.106+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-01T06:00:58.107+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-01T06:02:00.223+0000] {fetch_and_store_data.py:162} INFO - Insertados 15000 registros en tabla diabetes_validation para validation batch 0 usando to_sql
[2025-05-01T06:02:00.290+0000] {fetch_and_store_data.py:117} INFO - Obteniendo validation batch 1 desde http://datapi:80/get-validation-batch/?batch_number=1
[2025-05-01T06:02:01.587+0000] {fetch_and_store_data.py:134} INFO - Obtenidos 5353 registros de validation batch 1
[2025-05-01T06:02:01.588+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-01T06:02:11.380+0000] {fetch_and_store_data.py:162} INFO - Insertados 5353 registros en tabla diabetes_validation para validation batch 1 usando to_sql
[2025-05-01T06:02:11.396+0000] {fetch_and_store_data.py:226} INFO - Completado procesamiento de validation: 20353 registros en total
[2025-05-01T06:02:11.400+0000] {python.py:237} INFO - Done. Returned value was: 20353
[2025-05-01T06:02:11.400+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-01T06:02:11.436+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_diabetes_data, task_id=process_validation_data.process_validation_batches, execution_date=20250501T054205, start_date=20250501T060053, end_date=20250501T060211
[2025-05-01T06:02:11.663+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-01T06:02:11.690+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T06:02:11.692+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
