[2025-05-01T05:31:05.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-01T05:31:05.299+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_diabetes_data.process_train_data.process_train_batches manual__2025-05-01T05:23:47.993718+00:00 [queued]>
[2025-05-01T05:31:05.319+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_diabetes_data.process_train_data.process_train_batches manual__2025-05-01T05:23:47.993718+00:00 [queued]>
[2025-05-01T05:31:05.320+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2025-05-01T05:31:05.347+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_train_data.process_train_batches> on 2025-05-01 05:23:47.993718+00:00
[2025-05-01T05:31:05.368+0000] {standard_task_runner.py:63} INFO - Started process 405 to run task
[2025-05-01T05:31:05.376+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_diabetes_data', 'process_train_data.process_train_batches', 'manual__2025-05-01T05:23:47.993718+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_store_data.py', '--cfg-path', '/tmp/tmpa9ka0l31']
[2025-05-01T05:31:05.385+0000] {standard_task_runner.py:91} INFO - Job 110: Subtask process_train_data.process_train_batches
[2025-05-01T05:31:05.494+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_diabetes_data.process_train_data.process_train_batches manual__2025-05-01T05:23:47.993718+00:00 [running]> on host 8fe9b8e6dafd
[2025-05-01T05:31:05.646+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_diabetes_data' AIRFLOW_CTX_TASK_ID='process_train_data.process_train_batches' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T05:23:47.993718+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T05:23:47.993718+00:00'
[2025-05-01T05:31:05.648+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-01T05:31:05.705+0000] {fetch_and_store_data.py:189} INFO - Procesando 5 batches para train
[2025-05-01T05:31:05.705+0000] {fetch_and_store_data.py:117} INFO - Obteniendo train batch 0 desde http://datapi:80/get-batch/?batch_number=0
[2025-05-01T05:31:09.920+0000] {fetch_and_store_data.py:129} INFO - Obtenidos 15000 registros de train batch 0
[2025-05-01T05:31:09.922+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-01T05:31:09.923+0000] {base.py:84} INFO - Using connection ID 'mysql_diabetes_conn' for task execution.
[2025-05-01T05:31:10.574+0000] {fetch_and_store_data.py:173} ERROR - Error procesando train batch 0: '<' not supported between instances of 'NoneType' and 'str'
[2025-05-01T05:31:10.575+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-01T05:31:10.575+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_and_store_data.py", line 193, in process_dataset
    records_inserted = fetch_and_store_batch(
  File "/opt/airflow/dags/fetch_and_store_data.py", line 167, in fetch_and_store_batch
    connection.execute(text(sql), values)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1553, in _execute_clauseelement
    keys = sorted(distilled_params[0])
TypeError: '<' not supported between instances of 'NoneType' and 'str'
[2025-05-01T05:31:10.608+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fetch_and_store_diabetes_data, task_id=process_train_data.process_train_batches, execution_date=20250501T052347, start_date=20250501T053105, end_date=20250501T053110
[2025-05-01T05:31:10.634+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 110 for task process_train_data.process_train_batches ('<' not supported between instances of 'NoneType' and 'str'; 405)
[2025-05-01T05:31:10.720+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-01T05:31:10.744+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T05:31:10.746+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
